artifacts-root: artifacts


data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sivaranjini00/wineQuality-Dataset/raw/main/WineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt

